config/routes.rb
Rails.application.routes.draw do

  get 'team_members/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root 'pages#home'

  get 'flash_exec', :to => 'application#flash_exec'

  get 'home', :to => 'pages#home'
  get 'art', :to => 'pages#art'

  get 'cart', :to => 'charges#cart'
  get 'checkout', :to => 'charges#new'
  post 'payment_success', :to => 'charges#create'

  get 'add_order_item', :to => 'order_items#add'
  get 'remove_order_item', :to => 'order_items#remove'
  get 'remove_all_order_items', :to => 'order_items#remove_all'
  get 'update_order_item_quantity', :to => 'order_items#update_quantity'

  get 'set_ma_student', :to => 'application#set_ma_student'

  resources :clothing_lines, :only => [:show]
  resources :items, :only => [:show]
  resources :team_members, :only => [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div id="main">
  <div id="flowers">
    <%= image_tag("red_flower.png", :id => "red-flower", :class => "flower", :style => "transform:translateX(-5em);") %>
    <%= image_tag("yellow_flower.png", :id => "yellow-flower", :class => "flower") %>
    <%= image_tag("blue_flower.png", :id => "blue-flower", :class => "flower", :style => "transform:translateX(5em);") %>
  </div>
  <a href="javascript:void(0);", onclick="scroll_to_store();">
    <p id="down_arrow_text" class="store_arrow_text">store</p>
    <%= image_tag("down_arrow.png", :id => "down_arrow", :class => "store_arrow") %>
  </a>
</div>

<div id="clothing_lines" class="colored_section store">
  <div class="trigger" id="store_trigger"></div>
  <h2 id="store_title">store</h2>
  <% cl_ordered = @clothing_lines.sort { |cl1, cl2| cl1.index <=> cl2.index } %>
  <% cl_ordered.each do |clothing_line| %>
    <% path = "missing_img.png" %>
    <% if !clothing_line.img_path.nil? && !clothing_line.img_path.empty? %>
      <% path = "clothing_line_imgs/#{clothing_line.img_path}" %>
    <% end %>
    <div class="img_wrapper <%= "unavailable" if !clothing_line.available %>" data-aos="fade-up">
      <% img = image_tag(path, :alt => clothing_line.name) %>
      <% name = clothing_line.name.downcase %>
      <% link = clothing_line_path(clothing_line) %>
      <% if clothing_line.available %>
        <%= link_to(img, link) %>
        <%= link_to(name, link, :class => "img_text") %>
      <% else %>
        <%= img %>

        <div class="img_text_wrapper">
          <p class="img_text main"><%= name %></p>
          <p class="img_text sub">coming soon</p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<script>

  $('#navbar h1').on('click', function(e){
      e.preventDefault();
      $('html, body').stop().animate({
         scrollTop: $('#main').offset().top
      }, 500);
  });

</script>

app/views/pages/myst.html.erb
<%= image_tag("myst_img.png", :id => "myst_img", :alt => "Mystery") %>