config/routes.rb
Rails.application.routes.draw do

  get 'team_members/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root 'pages#home'

  get 'flash_exec', :to => 'application#flash_exec'

  get 'home', :to => 'pages#home'
  get 'art', :to => 'pages#art'

  get 'cart', :to => 'charges#cart'
  get 'checkout', :to => 'charges#new'
  post 'payment_success', :to => 'charges#create'

  get 'add_order_item', :to => 'order_items#add'
  get 'remove_order_item', :to => 'order_items#remove'
  get 'remove_all_order_items', :to => 'order_items#remove_all'
  get 'update_order_item_quantity', :to => 'order_items#update_quantity'

  get 'set_ma_student', :to => 'application#set_ma_student'

  resources :clothing_lines, :only => [:show]
  resources :items, :only => [:show]
  resources :team_members, :only => [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :clothing_line

  validates_presence_of :product_id
  validates_presence_of :name
  validates_presence_of :price
  validates_presence_of :img_path
  validates_presence_of :num_imgs

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require "stripe"

  def show
    @item = Item.friendly.find(params[:id])
    @product = Stripe::Product.retrieve(@item.product_id)
    @clothing_line = @item.clothing_line

    @img_paths = []
    if @item.num_imgs > 0
      for i in 1..@item.num_imgs
        @img_paths << "#{@item.img_path}/#{i}"
      end
    end

    # check that item name and retrieved product name match
    if @product.name.downcase != @item.name.downcase
      return error
    end

    # check that retrieved product has an sku
    if @product.skus.data.empty?
      return error
    end

    # check that item price and retrieved sku prices match
    @product.skus.data.each do |sku|
      if sku.price/100 != @item.price
        return error
      end
    end

    @back_arrow_info = { :name => @clothing_line.name.length>8 ? @clothing_line.name.truncate(11) : @clothing_line.name, :link => flash_exec_path(:exec => "scroll_to_store", :url => clothing_line_path(@clothing_line)) }

    @meta_title = meta_title @item.name
    @meta_description = "Voyage item – #{@item.name}"
  end

  private

  def error
    flash[:error] = "Sorry, there is a technical problem with displaying this item.  Voyage team has been notified."
    redirect_to(clothing_line_path(@clothing_line))
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/show.html.erb
<div id="item" class="colored_section top store">
  <div class="trigger" id="item_trigger"></div>
  <h2 id="item_title"><%= @product.name %></h2>
  <div id="back_arrow_wrapper">
    <%= render :partial => 'layouts/back_arrow', :locals => { name: @back_arrow_info[:name], link: @back_arrow_info[:link] } %>
  </div>
  <div id="imgs_wrapper" data-aos="fade-up" class=<%= "more_than_one" if @img_paths.length > 1 %>>
    <% if @img_paths.length > 1 %>
      <div id="img_previews">
        <% @img_paths.each_with_index do |img_path, i| %>
          <% img_asset_path = asset_path("item_imgs/#{img_path}") %>
          <label for=<%= "img_preview_selection_#{i}" %> id=<%= i == @img_paths.length-1 ? "label_last" : "label_#{i}" %> onmouseover="update_main_image('<%= img_asset_path %>', 'img_preview_selection_<%= i %>');">
            <%= radio_button_tag(:preview_img_selection, nil, i == 0, :id => "img_preview_selection_#{i}") %>
            <div class="img_preview">
              <%= image_tag("item_imgs/#{img_path}", :alt => @product.name) %>
            </div>
          </label>
        <% end %>
      </div>
    <% end %>
    <% path = !@img_paths.empty? ? "item_imgs/#{@img_paths[0]}" : "missing_img" %>
    <div id="img_main">
      <%= image_tag(path, :alt => @product.name) %>
    </div>
  </div>
  <div id="item_info" data-aos="fade-up">
    <% price = @product.skus.data.first.price %>
    <p id="item_price"><%= number_to_currency(price/100) %></p>
    <%= form_tag(add_order_item_path, id: "add_item_form", method: "get", remote: true) do %>
      <%= hidden_field_tag(:item_id, @item.id) %>
      <%= hidden_field_tag(:product_id, @product.id) %>
      <%= hidden_field_tag(:product_name, @product.name) %>
      <div id="size_radio_buttons">
        <% @product.skus.data.each_with_index do |sku, i| %>
          <label for=<%= "size_radio_button_#{i}" %>>
            <%= radio_button_tag(:sku_info, {:id => sku.id, :quantity_available => sku.inventory.quantity, :price => sku.price, :size => sku.attributes.size}, sku == @product.skus.data.first, :id => "size_radio_button_#{i}") %>
            <span class="radio_button_span"><p><%= sku.attributes.size %></p></span>
            <% unless sku.inventory.quantity.nil? %>
              <%= label_tag(:sku_id, sku.inventory.quantity > 0 ? "#{sku.inventory.quantity} in stock" : "out of stock", :class => "quantity_available_label") %>
            <% end %>
          </label>
        <% end %>
      </div>
      <div id="quantity_select_wrapper">
        <%= label_tag(:quantity, "QTY") %>
        <%= select_tag(:quantity, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9]), :id => "quantity_select") %>
      </div>
      <%= submit_tag("add to cart", :onclick => "scroll_to_cart(); show_loading_wheel();", :id => "item_submit") %>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('#add_item_form').on('ajax:success', function(e, data, status, xhr){
      hide_loading_wheel();
    });
  });

  function update_main_image(img_path, rb_id) {
      document.querySelector('#img_main img').src = img_path;
      document.getElementById(rb_id).checked = true;
  }

  function scroll_to_cart() {
      $('html, body').stop().animate({
         scrollTop: $('#cart').offset().top
      }, 500);
  };
</script>