config/routes.rb
Rails.application.routes.draw do

  get 'team_members/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root 'pages#home'

  get 'flash_exec', :to => 'application#flash_exec'

  get 'home', :to => 'pages#home'
  get 'art', :to => 'pages#art'

  get 'cart', :to => 'charges#cart'
  get 'checkout', :to => 'charges#new'
  post 'payment_success', :to => 'charges#create'

  get 'add_order_item', :to => 'order_items#add'
  get 'remove_order_item', :to => 'order_items#remove'
  get 'remove_all_order_items', :to => 'order_items#remove_all'
  get 'update_order_item_quantity', :to => 'order_items#update_quantity'

  get 'set_ma_student', :to => 'application#set_ma_student'

  resources :clothing_lines, :only => [:show]
  resources :items, :only => [:show]
  resources :team_members, :only => [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action only: [:new] do
    check_quantities(false)
  end
  before_action only: [:create] do
    check_quantities(true)
  end

  def new
    if session["order_items"].empty?
      return redirect_to "/home"
    end

    @back_arrow_info = { :name => "cart", :link => flash_exec_path(:exec => "scroll_to_cart", :url => URI((!request.referer.nil? && !request.referer.include?("team_members")) ? request.referer : '/home').path) }

    @meta_title = meta_title "Checkout"
  end

  def create
    items = []
    session[:order_items].each do |order_item|
      items << { :type => 'sku', :parent => order_item['sku_id'], :quantity => order_item['quantity'] }
    end

    if items.empty?
      return redirect_to "/home"
    end

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :shipping => {
        :name => params[:stripeShippingName],
        :address => {
          :line1 => params[:stripeShippingAddressLine1],
          :city => params[:stripeShippingAddressCity],
          :state => params[:stripeShippingAddressState],
          :country => params[:stripeShippingAddressCountry],
          :postal_code => params[:stripeShippingAddressZip]
        }
      },
      :source => params[:stripeToken]
    )

    order = Stripe::Order.create(
      :currency => 'usd',
      :items => items,
      :customer => customer.id,
      :metadata => {
        :shipping_method => session[:shipping_method]['name']
      }
    )

    order.pay(
      :customer  => customer.id
    )

    customer.delete

    @order_id = order.id
    @amount = order.amount

    @back_arrow_info = { :name => "home", :link => '/home' }

    session[:order_items] = nil
    session[:shipping_method] = nil

    @meta_title = meta_title "Payment Success"

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to checkout_path
    end
  end

  private

  def check_quantities(order_created)
    unavailable_quantity_items = []

    session[:order_items].each_with_index do |order_item, i|
      sku = Stripe::SKU.retrieve(order_item['sku_id'])

      unless sku.inventory.quantity.nil?
      quantity_available = sku.inventory.quantity.to_i
        if order_item['quantity'].to_i > quantity_available
          if quantity_available == 0
            session[:order_items].delete_at(i)
          else
            order_item['quantity'] = quantity_available
          end
          item_listing = "'#{order_item['name']} #{order_item['size'].upcase}'"
          if i > 0 && i == session[:order_items].length-1
            item_listing.prepend("and ")
          end
          unavailable_quantity_items << item_listing
        end
      end
    end

    if !unavailable_quantity_items.empty?
      error_message_lines = ["", ""]

      error_message_lines[0] = "#{quantity_error_beg(order_created)}  #{order_cancel_error}" if order_created
      error_message_lines[1] = quantity_error_end(unavailable_quantity_items)

      if order_created
        flash[:order_error_line1] = error_message_lines[0]
        flash[:order_error_line2] = error_message_lines[1]
      else
        flash[:error] = error_message_lines[1]
      end

      redirect_to checkout_path
    end
  end

  def quantity_error_beg
    "Order canceled due to quantity issue."
  end

  def quantity_error_end(unavailable_quantity_items)
    if unavailable_quantity_items.length == 1
      "The requested quantity for #{unavailable_quantity_items[0]} is no longer available, and has been adjusted in cart."
    elsif unavailable_quantity_items.length > 1
      uq_items_list = unavailable_quantity_items.length > 2 ? unavailable_quantity_items.join(", ") : unavailable_quantity_items.join(" ")
      "The requested quantities for #{uq_items_list} are no longer available, and have been adjusted in cart."
    end
  end

  def order_cancel_error
    "Your card was not charged.  If paid in Bitcoin, you will receive a refund email within a few days.  Please contact support with any questions."
  end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div id="payment_success" class="colored_section top">
  <div id="cart"></div>
  <div class="trigger" id="payment_success_trigger"></div>
  <h2 id="payment_success_title">Payment Success!</h2>
  <div id="back_arrow_wrapper">
    <%= render :partial => 'layouts/back_arrow', :locals => { name: @back_arrow_info[:name], link: @back_arrow_info[:link] } %>
  </div>
  <div id="payment_success_content" data-aos="fade-up">
    <p>Thanks, you paid <strong><%= number_to_currency(@amount/100) %></strong>!<br>You will receive a confirmation email for order '<%= @order_id %>' shortly.</p>
  </div>
</div>

app/views/charges/new.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<div id="checkout" class="colored_section top">
  <div class="trigger" id="checkout_trigger"></div>
  <h2 id="checkout_title">checkout</h2>
    <div id="back_arrow_wrapper">
      <%= render :partial => 'layouts/back_arrow', :locals => { name: @back_arrow_info[:name], link: @back_arrow_info[:link] } %>
    </div>
  <div id="checkout_content" data-aos="fade-up">
    <div id="cart">
      <div id="cart_content">
        <%= render :partial => 'layouts/cart', :locals => { order_items: @order_items } %>
        <% if @amount > 0 %>
          <div id="pay_buttons">
            <%= form_tag payment_success_path do %>
              <% amount = number_to_currency(@amount/100) %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-description="Voyage Store purchase"
                      data-image=<%= asset_path("icon.png") %>
                      data-label="pay"
                      data-amount="<%= @amount %>"
                      data-locale="auto"
                      data-shipping-address="true"
                      data-billing-address="true"
                      data-bitcoin="true"></script>
            <% end %>
            <%= button_tag("pay with apple pay", :id => "apple-pay-button") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  // Stripe.applePay.checkAvailability(function(available) {
  //   if (available) {
  //     document.getElementById('apple-pay-button').style.display = 'block';
  //   }
  // });
  //
  // document.getElementById('apple-pay-button').addEventListener('click', beginApplePay);
  // function beginApplePay() {
  //   var paymentRequest = {
  //     requiredShippingContactFields: ['postalAddress', 'emailAddress', 'givenName', 'familyName'],
  //     countryCode: 'US',
  //     currencyCode: 'USD',
  //     total: {
  //       label: 'Voyage Store',
  //       amount: '<%= @amount/100 %>'
  //     }
  //   };
  //
  //   var session = Stripe.applePay.buildSession(paymentRequest,
  //       function(result, completion) {
  //         $.post('/payment_success', {
  //           stripeToken: result.token.id,
  //           stripeEmail: result.shippingContact.emailAddress,
  //           stripeShippingName: result.shippingContact.givenName + result.shippingContact.familyName,
  //           stripeShippingAddressLine1: result.shippingContact.address_line1,
  //           stripeShippingAddressCity: result.shippingContact.locality,
  //           stripeShippingAddressState: result.shippingContact.administrativeArea,
  //           stripeShippingAddressCountry: result.shippingContact.country,
  //           stripeShippingAddressZip: result.shippingContact.postalCode
  //         }).done(function() {
  //           completion(ApplePaySession.STATUS_SUCCESS);
  //         }).fail(function() {
  //           completion(ApplePaySession.STATUS_FAILURE);
  //         });
  //
  //     });
  //
  //   session.oncancel = function() {
  //     console.log("User hit the cancel button in the payment window");
  //   };
  //
  //   session.begin();
  // }
</script>