config/routes.rb
Rails.application.routes.draw do

  get 'team_members/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  root 'pages#home'

  get 'flash_exec', :to => 'application#flash_exec'

  get 'home', :to => 'pages#home'
  get 'art', :to => 'pages#art'

  get 'cart', :to => 'charges#cart'
  get 'checkout', :to => 'charges#new'
  post 'payment_success', :to => 'charges#create'

  get 'add_order_item', :to => 'order_items#add'
  get 'remove_order_item', :to => 'order_items#remove'
  get 'remove_all_order_items', :to => 'order_items#remove_all'
  get 'update_order_item_quantity', :to => 'order_items#update_quantity'

  get 'set_ma_student', :to => 'application#set_ma_student'

  resources :clothing_lines, :only => [:show]
  resources :items, :only => [:show]
  resources :team_members, :only => [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_back_arrow.html.erb
<%= link_to(image_tag("left_arrow.png"), link) %>
<%= link_to(name.downcase, link, :class => "arrow_text") %>

app/views/layouts/_cart.html.erb
<% if flash[:cart_error].present? %>
  <div id="cart_error" data-aos="fade-up">
    <p><%= flash[:cart_error] %></p>
  </div>
<% end %>
<% if flash[:cart_notice].present? %>
  <div id="cart_notice" data-aos="fade-up">
    <p><%= flash[:cart_notice] %></p>
  </div>
<% end %>
<p <%= !@order_items.nil? && !@order_items.empty? ? "hidden" : "" %> id="empty_text">there's nothing here, go get some <%= link_to("stuff", "javascript:void(0);", :onclick => "scroll_to_store();") %>!</p>
<div <%= @order_items.nil? || @order_items.empty? ? "hidden" : "" %> id="cart_content_stuff">
  <%= link_to("mercersburg academy#{@ma_student ? "!" : "?"}", "javascript:void(0);", :id => "ma_student_link", :class => @ma_student ? "selected" : "", :onclick => "set_ma_student();", :remote => true) if params[:controller] != "charges" %>
  <table id="order_items_table">
    <tr>
      <th class="product_col">Product</th>
      <th class="size_col">Size</th>
      <th class="qty_col">QTY</th>
      <th class="price_col">Price</th>
    </tr>
    <% order_items.each_with_index do |order_item, i| %>
      <% unless order_item.nil? %>
        <% puts "order_item" + order_item.to_s %>
        <tr id="order_item_<%= i %>">
          <td class="product_col"><%= link_to(order_item['name'], item_path(Item.find_by_id(order_item['item_id']))) %></td>
          <td class="size_col"><%= order_item['size'] %></td>
          <% if params[:controller] != "charges" %>
            <td class="qty_col"><%= select_tag(:quantity, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9], order_item['quantity'].to_i), :id => "order_item_#{i}_quantity_select", :onchange => "update_order_item_quantity(#{i})") %></td>
          <% else %>
            <td class="qty_col"><%= order_item['quantity'] %></td>
          <% end %>
          <td class="price_col"><%= number_to_currency(order_item['price']/100) %></td>
          <td class="remove_col"><%= link_to("x", "javascript:void(0);", :onclick => "remove_order_item(#{i});", :remote => true) %></td>
        </tr>
      <% end %>
    <% end %>
    <% if params[:controller] == "charges" %>
      <tr id="shipping">
        <td class="product_col"><%= session[:shipping_method]['name'] %></td>
        <td class="size_col"></td>
        <td class="qty_col"></td>
        <td class="price_col"><%= number_to_currency(session[:shipping_method]['cost']) %></td>
      </tr>
    <% end %>
  </table>
  <% if params[:controller] == "charges" %>
    <p id="total"><%= number_to_currency @amount/100 %></p>
  <% end %>
  <div id="cart_bottom_links">
    <%= link_to("empty", "javascript:void(0);", :id => "empty_cart_link", :onclick => "remove_all_order_items();", :remote => true) %>
    <%= link_to("checkout", checkout_path, :id => "checkout_link") %>
  </div>
</div>

<script>
  var checkout_link = document.getElementById('checkout_link')
  var ogHref = checkout_link.href
  var ma_student_link = document.getElementById('ma_student_link')

  function set_ma_student() {
    var data = ""

    checkout_link.href = "javascript:void(0);"
    checkout_link.className = "disabled_link"

    show_loading_wheel()

    $.ajax({
      url: '/set_ma_student',
      data: data,
      type: 'get'
    })
    .done(function(data) {
      if (ma_student_link.className.includes("selected")) {
        ma_student_link.className = "";
        ma_student_link.innerHTML = "mercersburg academy?"
      }
      else {
        ma_student_link.className = "selected";
        ma_student_link.innerHTML = "mercersburg academy!"
      }

      checkout_link.href = ogHref
      checkout_link.className = ""
      hide_loading_wheel()
    })
  }

  function remove_all_order_items() {
    var data = ""

    checkout_link.href = "javascript:void(0);"
    checkout_link.className = "disabled_link"

    show_loading_wheel()

    $.ajax({
      url: '/remove_all_order_items',
      data: data,
      type: 'get'
    })
    .done(function(data) {
      checkout_link.href = ogHref
      checkout_link.className = ""
      hide_loading_wheel()
    })
  }

  function remove_order_item(index) {
    var data = "index=" + index

    checkout_link.href = "javascript:void(0);"
    checkout_link.className = "disabled_link"

    show_loading_wheel()

    $.ajax({
      url: '/remove_order_item',
      data: data,
      type: 'get'
    })
    .done(function(data) {
      checkout_link.href = ogHref
      checkout_link.className = ""
      hide_loading_wheel()
    })
  }

  function update_order_item_quantity(index) {
    var e = document.getElementById('order_item_' + index + '_quantity_select');
    var quantity = e.options[e.selectedIndex].text;
    var data = "index=" + index + "&quantity=" + quantity;

    checkout_link.href = "javascript:void(0);"
    checkout_link.className = "disabled_link"

    show_loading_wheel()

    $.ajax({
      url: '/update_order_item_quantity',
      data: data,
      type: 'get'
    })
    .done(function(data) {
      checkout_link.href = ogHref
      checkout_link.className = ""
      hide_loading_wheel()
    })
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @meta_title ? @meta_title : ApplicationController::BRAND_NAME %></title>
    <% if @meta_description.present? %>
      <meta name="description" content="<%= @meta_description %>">
    <% end %>

    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=1">
    <%= csrf_meta_tags %>

    <% if error_present %>
      <style>
        #navbar {
          box-shadow: none !important;
        }
      </style>
    <% end %>

    <%= stylesheet_link_tag    'application', Rails.application.assets.find_asset(params[:controller]) ? params[:controller] : 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', Rails.application.assets.find_asset(params[:controller]) ? params[:controller] : 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag('mobile_application') if mobile_device? %>
    <%= javascript_include_tag('flowers_animation') if !mobile_device? %>

    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <% unapproved_controllers = ["devise/sessions"] %>
    <% if !unapproved_controllers.include? params[:controller] %>
      <div id="navbar">
        <% unless @back_arrow_info.nil? %>
          <div id="back_arrow_nav_wrapper">
            <%= render :partial => 'layouts/back_arrow', :locals => { name: @back_arrow_info[:name], link: @back_arrow_info[:link] } %>
          </div>
        <% end %>
        <h1><%= link_to("voyage", root_path) %></h1>
        <ul id="navlinks">
          <li id="about_us_link"><%= link_to("about us", "javascript:void(0);", :onclick => "scroll_to_element('#about_us');") %></li>
          <li id="contact_link"><%= link_to("contact", "javascript:void(0);", :onclick => "scroll_to_element('#contact');") %></li>
          <li id="cart_link"><%= link_to("cart", "javascript:void(0);", :onclick => "scroll_to_element('#cart');") if params[:controller] != "team_members" %></li>
        </ul>
        <%= image_tag("loading.svg", :id => "loading_wheel") %>
      </div>
      <% if flash[:order_error_line1].present? && flash[:order_error_line2].present? %>
        <div class="error_message">
          <p><%= flash[:order_error_line1] %><br><%= flash[:order_error_line2] %></p>
        </div>
      <% elsif flash[:error].present? %>
        <div class="error_message">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    <% end %>
    <div id="content">
      <%= yield %>
    </div>
    <% if !unapproved_controllers.include? params[:controller] %>
      <div id="footer">
        <% if params[:controller] != "charges" && params[:controller] != "team_members" %>
          <div id="cart" class="colored_section">
            <div class="trigger" id="cart_trigger"></div>
            <h2 id="cart_title">cart</h2>
            <div id="cart_content" data-aos="fade-up">
              <%= render :partial => 'layouts/cart', :locals => { order_items: @order_items } %>
            </div>
          </div>
        <% end %>
        <% if params[:controller] != "team_members" %>
          <div id="about_us" class="colored_section">
            <div class="trigger" id="about_us_trigger"></div>
            <h2 id="about_us_title">about us</h2>
            <% tm_ordered = TeamMember.all.sort { |tm1, tm2| tm1.index <=> tm2.index } %>
            <% tm_ordered.each_with_index do |team_member, i| %>
              <% path = "missing_img.png" %>
              <% if !team_member.img_path.nil? && !team_member.img_path.empty? %>
                <% path = "team_member_imgs/#{team_member.img_path}" %>
              <% end %>
              <div class="img_wrapper <%= "last" if i == tm_ordered.size-1 %>" data-aos="fade-up">
                <%= link_to(image_tag(path, :alt => team_member.name), team_member_path(team_member)) %>
                <%= link_to(team_member.name.downcase, team_member_path(team_member), :class => "img_text main") %>
                <%= link_to(team_member.role.downcase, team_member_path(team_member), :class => "img_text sub") %>
              </div>
            <% end %>
            <a href="https://www.instagram.com/voyagegang/" id="insta_link" class="special_link" target="_blank" rel="nofollow", data-aos="fade-up">@voyagegang</a>
          </div>
        <% end %>
        <div id="contact" class="colored_section">
          <div class="trigger" id="contact_trigger"></div>
          <h2 id="contact_title">contact</h2>
          <a href="mailto:support@voyagealone.com" id="email_link" class="special_link" rel="nofollow", data-aos="fade-up">support@voyagealone.com</a>
        </div>
      </div>
    <% end %>

    <script>
      AOS.init();

      var touch = 'ontouchstart' in document.documentElement
            || navigator.maxTouchPoints > 0
            || navigator.msMaxTouchPoints > 0;

      if (touch) { // remove all :hover stylesheets
          try { // prevent exception on browsers not supporting DOM styleSheets properly
              for (var si in document.styleSheets) {
                  var styleSheet = document.styleSheets[si];
                  if (!styleSheet.rules) continue;

                  for (var ri = styleSheet.rules.length - 1; ri >= 0; ri--) {
                      if (!styleSheet.rules[ri].selectorText) continue;

                      if (styleSheet.rules[ri].selectorText.match(':hover')) {
                          styleSheet.deleteRule(ri);
                      }
                  }
              }
          } catch (ex) {}
      }

      var loading_wheel_timer;

      function show_loading_wheel() {
        loading_wheel_timer = setTimeout(function() {
          document.getElementById('loading_wheel').style.display = "block";
        }, 500);
      }

      function hide_loading_wheel() {
        clearTimeout(loading_wheel_timer);
        document.getElementById('loading_wheel').style.display = "none";
      }

      var userAgent = window.navigator.userAgent
      var isSafari = /iP(ad|hone|od).+Version\/[\d\.]+.*Safari/i.test(navigator.userAgent)

      function scroll_to_element(element, time) {
        var distance = $(element).offset().top + ((userAgent.match(/iPhone/i) || userAgent.match(/iPad/i)) && isSafari ? 38 : 0)
        $('html, body').stop().animate({
           scrollTop: distance
        }, time == null ? 500 : time);
      }

      function scroll_to_store() {
        var distance = $('.store').offset().top + (userAgent.match(/iPhone/i) || userAgent.match(/iPad/i) && isSafari ? 38 : 0)
        $('html, body').stop().animate({
           scrollTop: distance
        }, 500);
      }
    </script>

    <% if flash[:exec] == "scroll_to_store" %>
      <script>scroll_to_store();</script>
    <% end %>

    <% if flash[:exec] == "scroll_to_cart" %>
      <script>scroll_to_element(document.getElementById('cart'));</script>
    <% end %>

    <% if flash[:exec] == "scroll_to_about_us" %>
      <script>scroll_to_element(document.getElementById('about_us'));</script>
    <% end %>
  </body>
</html>

app/views/layouts/no_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <%= yield %>
  </body>
</html>